name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code with commit history
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last two commits for change detection

      # Step 2: Set up JDK (required if building Java project)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project
      - name: Build project with Maven
        run: mvn clean package -DskipTests  # Skip tests for faster build

      # Step 4: Set Commit ID for Tagging
      - name: Set Commit ID as Tag
        run: echo "COMMIT_ID=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      # Step 5: Check which services changed
      - name: Check changed files
        id: changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^service-hello/'; then
            echo "HELLO_CHANGED=true" >> $GITHUB_ENV
          fi
          if git diff --name-only HEAD^ HEAD | grep -q '^service-world/'; then
            echo "WORLD_CHANGED=true" >> $GITHUB_ENV
          fi

      # Step 6: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 7: Install Azure CLI containerapp extension
      - name: Install Azure CLI containerapp extension
        run: |
          az extension add --name containerapp --upgrade

      # Step 8: Login to Azure Container Registry (if any service changed)
      - name: Login to Azure Container Registry
        if: env.HELLO_CHANGED == 'true' || env.WORLD_CHANGED == 'true'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 9: Build and Push Docker Image for service-hello
      - name: Build and Push service-hello
        if: env.HELLO_CHANGED == 'true'
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/service-hello:${{ env.COMMIT_ID }} ./service-hello
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/service-hello:${{ env.COMMIT_ID }}

      # Step 10: Build and Push Docker Image for service-world
      - name: Build and Push service-world
        if: env.WORLD_CHANGED == 'true'
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/service-world:${{ env.COMMIT_ID }} ./service-world
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/service-world:${{ env.COMMIT_ID }}

      # Step 11: Deploy service-hello to Azure Container Apps
      - name: Deploy service-hello
        if: env.HELLO_CHANGED == 'true'
        run: |
          az containerapp update \
            --name javapochelloservice \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/service-hello:${{ env.COMMIT_ID }}

      # Step 12: Deploy service-world to Azure Container Apps
      - name: Deploy service-world
        if: env.WORLD_CHANGED == 'true'
        run: |
          az containerapp update \
            --name javapocworldservice \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/service-world:${{ env.COMMIT_ID }}
